### ISSUE TITLE
unassertify and unassert-cli

### ISSUE THREAD

**Issue by davidmarkclements** [apparatus/mu#30]
I like that we're going with the `assert` approach (apparently known as design by contract)

I think we should go all out with `assert` and just `assert` the crap out of everything

And then "unassert" strip all asserts (in a production server build and browserify build) using http://npm.im/unassert-cli and http://npm.im/unassertify

The only caveat I can think of, is care should be taken when defensive programming is required for production scenarios - in which case don't use assert, use an if statement

**Comment by davidmarkclements** [comment]
if agreeable and successful we could also promote this approach for building services with mu (kind of a nice answer to the schemaless question too)

**Comment by davidmarkclements** [comment]
also https://www.npmjs.com/package/power-assert looks amazing - same api as assert, just generates more descriptive messages on failure (great for dev)

**Comment by mcollina** [comment]
I'm 👎 on having to transpile the code for production to remove the asserts.

I do not know what is the performance impact of asserts, so it is hard to tell as there are no benchmarks for mu.

If the cost of doing asserts is too high, we can make them `noop`, based on `NODE_ENV=production`.

In the end the cost of assert is mainly in the frontend, because it will add lots of precious bytes to the payload. Maybe we can replace assert with `if (weNeedToFail) { throw new Error('muahah') }`, and be done with it.

**Comment by davidmarkclements** [comment]
Ok sure, making it a noop in prod should suffice

I think the idea is that the code runs independent of the asserts, they're simply checks for dev errors (user errors would require if statements)

So I'm saying, just strip them right out 

1. Server: If prod assert = noop
2. Browser: specify unnassertify in package.json, removes all asserts in browser code

Either that or avoid assert

**Comment by davidmarkclements** [comment]
having discussed with @pelger .. this is possibly not a good idea
