### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by StarpTech** [apparatus/mu#58]
Hi
why has a failed dispatch action the field `err` in the result payload?

```
function(err, result) {

}
```
`err = <error>`
`result = { err: <error> }`

if you pass an error and a result the payload looks like 

```
result: { err: <error>, <additional-result-> }
```

**Comment by davidmarkclements** [comment]
good question - it's a by product or serialisation at the transport layer (we have to get the error across services, and we treat it slightly differently to network and transport errors because it's to be handled by the consumer) but we probably shouldn't be revealing it to the user

we also need to think about (at the transport level) whether .err should be attached to response or should instead have it's own first-level field in the "packet", or perhaps should be in the `protocol` field as say, `serviceErr` or something 

@pelger, @mcollina thoughts?

**Comment by mcollina** [comment]
From a user perspective, it needs to go in the first argument of the function.
From a protocol perspective, I think we should wrap messages and add all those info without changing the msg itself.

**Comment by davidmarkclements** [comment]
yah it goes into first arg always atm - 
I think we should also remove from being nested in second arg at user level

So I think then, instead of adding it to packet.response.err we should add it to packet.err (https://github.com/apparatus/mu/blob/master/packages/mu-transport/index.js#L60-L68)

**Comment by mcollina** [comment]
Yes!!
