### ISSUE TITLE
Add Bloomrun over Patrun

### ISSUE THREAD

**Issue by mcdonnelldean** [apparatus/mu#6]
Bloomrun is far faster (3x - 10x) than Patrun, it also supports index & depth first (which are equally valid).

The only concern I have right now is mu uses `*` over `\*\` for regex. This means we either,

- Change mu to do the conversion
- Change bloomrun to do the conversion

@mcollina thoughts on this?

**Comment by mcollina** [comment]
My opinion is that using `'*'` as a special thing is wrong. That's a string and not a "pattern", it means equality.

We do not have to be worried about backward compatibility here, so I say let's _not do it_. Convert the examples to `/.*/`, which is the functional equivalent.

However, I think we should have `*` as a special thing in tinysonic (maybe behind an option), so that it's easy to use that in string patterns.

**Comment by mcdonnelldean** [comment]
@mcollina Yeah agreed. I spoke to @pelger too. Since it's functionally the same it's fine.
